In [1]:
# -*- coding: UTF-8 -*-
import pandas as pd
import numpy as np
import time
df_train = pd.read_csv('../bus_data/stationmap/train_amap_correct.csv')
df_train['station_id'] = None
df_train['name'] = None
df_train['real_longitude'] = np.NaN
df_train['real_latitude'] = np.NaN

In [2]:
df_train

,O_LINENO,O_UP,STATION,O_LONGITUDE,O_LATITUDE,longitude_amap,latitude_amap,station_id,name,real_longitude,real_latitude
0,1,0,1,117.198,39.1274,117.204307,39.128437,None,None,NaN,NaN
1,1,0,2,117.199,39.1258,117.205306,39.126834,None,None,NaN,NaN
2,1,0,3,117.195,39.1224,117.201312,39.123439,None,None,NaN,NaN
3,1,0,4,117.192,39.1207,117.198317,39.121743,None,None,NaN,NaN
4,1,0,5,117.187,39.1229,117.193325,39.123953,None,None,NaN,NaN
5,1,0,6,117.178,39.1252,117.184342,39.126271,None,None,NaN,NaN
6,1,0,7,117.179,39.1288,117.185341,39.129871,None,None,NaN,NaN
7,1,0,8,117.183,39.1293,117.189334,39.130364,None,None,NaN,NaN
8,1,0,9,117.186,39.1327,117.192329,39.133761,None,None,NaN,NaN
9,1,0,10,117.186,39.1347,117.192329,39.135762,None,None,NaN,NaN
10,1,0,11,117.181,39.1359,117.187338,39.136971,None,None,NaN,NaN
11,1,0,12,117.180,39.1394,117.186341,39.140476,None,None,NaN,NaN
12,1,0,13,117.180,39.1422,117.186341,39.143277,None,None,NaN,NaN
13,1,0,14,117.182,39.1431,117.188337,39.144174,None,None,NaN,NaN
14,1,0,15,117.189,39.1517,117.195326,39.152766,None,None,NaN,NaN
15,1,0,16,117.192,39.1555,117.198321,39.156564,None,None,NaN,NaN
16,1,0,17,117.194,39.1574,117.200318,39.158461,None,None,NaN,NaN
17,1,0,18,117.197,39.1593,117.203313,39.160358,None,None,NaN,NaN
18,1,0,19,117.200,39.1628,117.206309,39.163855,None,None,NaN,NaN
19,1,0,20,117.211,39.1650,117.217294,39.166040,None,None,NaN,NaN
20,1,0,21,117.214,39.1650,117.220291,39.166036,None,None,NaN,NaN
21,1,0,22,117.218,39.1653,117.224287,39.166332,None,None,NaN,NaN
22,1,0,23,117.220,39.1670,117.226285,39.168031,None,None,NaN,NaN
23,1,0,24,117.216,39.1699,117.222289,39.170937,None,None,NaN,NaN
24,1,0,25,117.218,39.1729,117.224287,39.173936,None,None,NaN,NaN
25,1,0,26,117.221,39.1743,117.227285,39.175334,None,None,NaN,NaN
26,1,0,27,117.225,39.1766,117.231282,39.177632,None,None,NaN,NaN
27,1,0,28,117.229,39.1774,117.235280,39.178429,None,None,NaN,NaN
28,1,0,29,117.231,39.1750,117.237279,39.176026,None,None,NaN,NaN
29,1,0,30,117.233,39.1729,117.239278,39.173923,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
22343,61102,1,21,117.102,39.2688,117.108448,39.270054,None,None,NaN,NaN
22344,61102,1,22,117.104,39.2629,117.110448,39.264150,None,None,NaN,NaN
22345,61102,1,23,117.105,39.2587,117.111448,39.259947,None,None,NaN,NaN
22346,61102,1,24,117.108,39.2544,117.114448,39.255644,None,None,NaN,NaN
22347,61102,1,25,117.117,39.2340,117.123443,39.235228,None,None,NaN,NaN
22348,61102,1,26,117.119,39.2286,117.125442,39.229823,None,None,NaN,NaN
22349,61102,1,27,117.121,39.2240,117.127440,39.225219,None,None,NaN,NaN
22350,61102,1,28,117.128,39.2176,117.134434,39.218808,None,None,NaN,NaN
22351,61102,1,29,117.131,39.2140,117.137431,39.215202,None,None,NaN,NaN
22352,61102,1,30,117.134,39.2103,117.140427,39.211496,None,None,NaN,NaN
22353,61102,1,31,117.143,39.1995,117.149414,39.200677,None,None,NaN,NaN
22354,61102,1,32,117.150,39.1934,117.156402,39.194562,None,None,NaN,NaN
22355,61102,1,33,117.157,39.1881,117.163389,39.189247,None,None,NaN,NaN
22356,61102,1,34,117.160,39.1858,117.166384,39.186940,None,None,NaN,NaN
22357,61102,1,35,117.169,39.1818,117.175366,39.182921,None,None,NaN,NaN
22358,61102,1,36,117.174,39.1751,117.180356,39.176208,None,None,NaN,NaN
22359,61102,1,37,117.176,39.1714,117.182352,39.172502,None,None,NaN,NaN
22360,61102,1,38,117.178,39.1692,117.184348,39.170297,None,None,NaN,NaN
22361,61102,1,39,117.180,39.1651,117.186344,39.166191,None,None,NaN,NaN
22362,61102,1,40,117.184,39.1601,117.190336,39.161181,None,None,NaN,NaN
22363,61102,1,41,117.186,39.1576,117.192332,39.158675,None,None,NaN,NaN
22364,61102,1,42,117.188,39.1561,117.194328,39.157171,None,None,NaN,NaN
22365,61102,1,43,117.189,39.1523,117.195326,39.153367,None,None,NaN,NaN
22366,61102,1,44,117.183,39.1431,117.189335,39.144172,None,None,NaN,NaN
22367,61102,1,45,117.180,39.1400,117.186341,39.141076,None,None,NaN,NaN
22368,61102,1,46,117.179,39.1335,117.185342,39.134574,None,None,NaN,NaN
22369,61102,1,47,117.180,39.1276,117.186339,39.128668,None,None,NaN,NaN
22370,61102,1,48,117.184,39.1267,117.190331,39.127760,None,None,NaN,NaN
22371,61102,1,49,117.194,39.1225,117.200313,39.123540,None,None,NaN,NaN
22372,61102,1,50,117.197,39.1212,117.203308,39.122234,None,None,NaN,NaN

In [3]:
df_real = pd.read_csv('../bus_data/stationmap/location_corrected.csv')
df_real

      station_id       name   longitude   latitude
0              0      247社区  117.337807  39.709927
1              1      奥克斯电气  117.010269  39.416382
2              2        奥兰里  117.252777  39.133121
3              3    奥林匹克博物馆  117.554939  38.927555
4              4       奥林花园  117.654144  39.044552
5              5        安乐村  117.362724  39.689865
6              6       安光小学  116.999702  39.217419
7              7        安光村  116.999611  39.223274
8              8      安光油墨厂  116.999649  39.221779
9              9        安太里  117.655975  39.017632
10            10        安定里  117.186646  39.165951
11            11        安泽里  117.136047  39.145187
12            12       安津医院  117.069290  39.233574
13            13       安裕新村  117.418961  40.039059
14            14        安达桥  117.424843  38.871178
15            15        安阳道  117.663864  38.993320
16            16         敖北  116.930908  39.308361
17            17       敖嘴村口  116.958267  39.312737
18            18         敖西  116.930908  39.308361
19            19       爱国东里  117.394356  38.670040
20            20       爱国北里  117.218575  39.098717
21            21        爱国里  117.220016  39.097752
22            22        爱营里  117.249550  39.146576
23            23        艾林庄  117.643242  39.455292
24            24        艾蒲庄  116.997688  39.319023
25            25       阿尔卑斯  117.235428  38.993500
26            26       鞍山西道  117.157745  39.113945
27            27        鞍山道  117.188660  39.120312
28            28      BBA公司  117.713768  39.051575
29            29       五号堤路  117.223724  39.074368
...          ...        ...         ...        ...
6029        6029        赵庄南  112.536469  37.922756
6030        6030        赵庄子  116.239403  40.060726
6031        6031       赵庄子村  116.832458  38.875572
6032        6032         赵本  117.652069  39.467297
6033        6033        赵沽里  117.249886  39.170387
6034        6034        赵温村  117.407166  39.253456
6035        6035      赵翰林庄村  117.248566  39.954449
6036        6036       赵苑小区  117.110329  39.153313
6037        6037        赵连庄  117.235802  38.794861
6038        6038     辰兴路佳宁道  117.132523  39.197834
6039        6039       造甲中学  117.454544  39.282444
6040        6040    造甲国道服务站  117.407872  39.292724
6041        6041      造甲工业区  117.437706  39.282700
6042        6042      造甲邮政所  117.451912  39.282478
6043        6043      造甲镇政府  117.431793  39.282909
6044        6044       造纸宿舍  117.310730  39.091541
6045        6045  造纸宿舍(张贵庄)  117.310730  39.091541
6046        6046        郑家套  117.402817  39.932892
6047        6047        郑家楼  116.887917  39.192200
6048        6048        郑州道  117.811913  38.999084
6049        6049        郑庄子  117.252625  39.091072
6050        6050   郑庄子[西青区]  116.984329  39.098854
6051        6051       郑庄子村  117.545265  39.002903
6052        6052         重工  117.728271  38.982819
6053        6053      重阳里南门  117.463348  38.844570
6054        6054       鑫银大厦  117.203323  39.096134
6055        6055       钻井公司  117.513802  38.691814
6056        6056        钻井路  117.693420  38.974426
6057        6057   镇政府[静海镇]  116.922920  38.929836
6058        6058        震新村  117.809563  39.278263

[6059 rows x 4 columns]

In [ ]:
a = time.time()
for i in range(len(df_train)):
    train_x = df_train.loc[i,'longitude_amap']
    train_y = df_train.loc[i,'latitude_amap']
    df_temp = df_real.copy()
    df_temp['distance'] = np.NaN
    for j in range(len(df_real)):
        real_x = df_real.loc[j,'longitude']
        real_y = df_real.loc[j,'latitude']
        distance = (train_x*1000 - real_x*1000)**2 + (train_y*1000 - real_y*1000)**2
        df_temp.loc[j,'distance'] = distance
    df_temp.sort_values(by=['distance'],inplace=True)
    index = df_temp.index[0]
    df_train.loc[i,'station_id'] = df_real.loc[index,'station_id']
    df_train.loc[i,'name'] = df_real.loc[index,'name']
    df_train.loc[i,'real_longitude'] = df_real.loc[index,'longitude']
    df_train.loc[i,'real_latitude'] = df_real.loc[index,'latitude']
    if i % 10 == 9:
        b = time.time()
        print('complete {},cost {}s.'.format(i+1,b-a))

In [ ]:
df_train

In [ ]:
df_train.to_csv('../bus_data/stationmap/match_result.csv',index=False)